# Generated by Django 4.2.7 on 2025-04-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=18)),
                ("user_password", models.CharField(max_length=8)),
                ("user_email", models.EmailField(max_length=50, unique=True)),
                ("user_role", models.CharField(max_length=10)),
            ],
        ),
    ]
